---
- hosts: all
  sudo: yes
  tasks:
   - name: Install add-apt-repository
     become: yes
     apt: name=software-properties-common state=latest
   - name: Add orcale Java Repository
     become: yes
     apt_repository: repo='ppa:webupd8team/java'
   - name: Accept Java 8 License
     become: yes
     debconf: name='oracle-java8-installer' question='shared/accepted-oracle-license-v1-1' value='true' vtype='select'
   - name: Install Oracle Java 8
     become: yes
     apt: name{{item}} state=latest
     with_items:
       - oracle-java8-installer
       - ca-certificates
       - oracle-java8-set-default
   - name: Create Folder
     become: yes
     file:
      path: /root/tomcat
      state: directory
      mode: 0755
      owner: ubuntu
      group: ubuntu
   - name: Download Tomcat
     become: yes
     get_url: url=https://archive.apache.org/dist/tomcat/tomcat-8/v8.0.27/bin/apache-tomcat-8.0.27.tar.gz dest=/root/tomcat
   - name: Extract Archive
     become: yes
     copy: src=/root/tomcat/apache-tomcat-8.0.27.tar.gz dest=/root/
   - name: Unarchiving on node machine
     unarchive: src=/root/apache-tomcat-8.0.27.tar.gz dest=/root/
   - name: Start apache-tomcat-8.0.27
     shell: /root/tomcat/apache-tomcat-8.0.27/bin/startup.sh
   - name: Copy tar file
     shell: cp /root/mnt/*.jar /root/apache-tomcat-8.0.27/webapps/

